#!/bin/bash
DIR=$(dirname $0)
PY_FILE="$DIR/main.py"
PYTHON="python"

if [ ! -e $PY_FILE ]; then
    echo "ERROR: misconfigured, cannot find $PY_FILE"
    exit 1
fi

if [ x"$1" = x"-r" ]; then
    shift
    $PYTHON $PY_FILE "$@"
else
    $PYTHON $PY_FILE "$@" | xmllint --format -
fi
