#!/bin/bash
CC="gcc"
CPP="gcc -E"
PARSE="/usr/bin/env perl6-m -I lib CRead.pl6"

if [ x"$1" = x"-r" ]; then
   ${CPP} $2 | grep -v '^#' | ${PARSE} -
else
   ${CPP} $1 | grep -v '^#' | ${PARSE} - | xmllint --format -
fi
